import SideBar from '@/components/SideBar'
import '@/styles/globals.css'

export const metadata = {
  title: 'DevPoint GPT',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex'>
          <SideBar/>

          {/** ClientProvider - Notification */}
          <div className='bg-[#343541] flex-1'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
